/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    private char senha;
    private String user = "admin", key = "1234";
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        senha = txtSenha.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        selMostrarSenha = new javax.swing.JCheckBox();
        btnEntrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setMaximumSize(new java.awt.Dimension(342, 430));
        setMinimumSize(new java.awt.Dimension(342, 430));
        setPreferredSize(new java.awt.Dimension(342, 430));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPERMERCADO VICWILL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 342, 69);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/icon-supermercado.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(129, 95, 100, 101);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/identificador.png"))); // NOI18N
        jLabel3.setText("Nome: ");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 210, 80, 24);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/senha.png"))); // NOI18N
        jLabel4.setText("Senha:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 240, 80, 24);

        txtUsuario.setMinimumSize(new java.awt.Dimension(8, 20));
        txtUsuario.setPreferredSize(new java.awt.Dimension(8, 20));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(149, 204, 110, 30);

        txtSenha.setMinimumSize(new java.awt.Dimension(8, 20));
        txtSenha.setPreferredSize(new java.awt.Dimension(8, 20));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(149, 239, 110, 30);

        selMostrarSenha.setText("Mostrar senha");
        selMostrarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selMostrarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(selMostrarSenha);
        selMostrarSenha.setBounds(144, 280, 110, 23);

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(130, 330, 90, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/exibirSenha.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(116, 279, 24, 24);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void login(){
        //Parte da verificação do login
        if (new String(txtSenha.getPassword()).equals(key)
                    && user.equals(txtUsuario.getText())) {
            JanelaInicial janelaInicial = new JanelaInicial();
            janelaInicial.setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Senha ou usuário incorreto", "ERROR", JOptionPane.ERROR_MESSAGE);
        
        }
        
    }
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        login();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        login();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        login();
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void selMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selMostrarSenhaActionPerformed
        //troca do icone do mostrar ou não a senha
        if (selMostrarSenha.isSelected()){
            txtSenha.setEchoChar('\u0000');
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/ocultarSenha.png")));
            selMostrarSenha.setText("Ocultar senha");
        } else {
            txtSenha.setEchoChar(senha);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/exibirSenha.png")));
            selMostrarSenha.setText("Mostrar senha");

        }
    }//GEN-LAST:event_selMostrarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox selMostrarSenha;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
